#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/everpal

PRODUCT_COPY_FILES += \
    vendor/xiaomi/everpal/proprietary/recovery/root/vendor/firmware/novatek_ts_ct_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_ct_fw.bin \
    vendor/xiaomi/everpal/proprietary/recovery/root/vendor/firmware/novatek_ts_ct_mp.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_ct_mp.bin \
    vendor/xiaomi/everpal/proprietary/recovery/root/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw.bin \
    vendor/xiaomi/everpal/proprietary/recovery/root/vendor/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_mp.bin \
    vendor/xiaomi/everpal/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/aurisys_param/sixth_param.txt:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_param/sixth_param.txt \
    vendor/xiaomi/everpal/proprietary/vendor/etc/aurisys_param/sixth_param_voip.txt:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_param/sixth_param_voip.txt \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/LDC_packdata_xiaomi.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi.dat \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/com.xiaomi.dcal.wd.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wd.golden \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/dof_mecp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dof_mecp.bin \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/goldResult_K16B_1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/goldResult_K16B_1.bin \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/goldResult_k16b_2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/goldResult_k16b_2.bin \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/hdrcheckerparamsettings.yml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdrcheckerparamsettings.yml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/intsense_config_undistort.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/intsense_config_undistort.bin \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/libalfpc_tuning.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/libalfpc_tuning.bin \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/model/dof_model/capture_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/dof_model/capture_cache \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/model/dof_model/capture_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/dof_model/capture_model \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/model/dof_model/capture_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/dof_model/capture_policy \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/model/rt_model/preview_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_model/preview_cache \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/model/rt_model/preview_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_model/preview_model \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/model/rt_model/preview_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_model/preview_policy \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/sr_params.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_params.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/everpal/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/elliptic_sensor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/elliptic_sensor.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/android.hardware.keymaster@4.1-service.beanpod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.1-service.beanpod.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek-64b.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek-64b.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/microtrust.bp_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.bp_kmsetkey_ca.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/microtrust.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/vpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vpud.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/xiaomi/everpal/proprietary/vendor/etc/libnfc-hal-st.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy \
    vendor/xiaomi/everpal/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy \
    vendor/xiaomi/everpal/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/st21nfc_conf.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st21nfc_conf.txt \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-arvr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-arvr.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-chg-only.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-chg-only.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-class0.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-mgame.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-navigation.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nolimits.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-video.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermal-youtube.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-youtube.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/everpal/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/xiaomi/everpal/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1_1.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1a_1.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/aw8697_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8697_haptic.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/aw8697_rtp_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8697_rtp_1.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/aw87xxx_pid_59_fm_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_pid_59_fm_0.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/aw87xxx_pid_59_music_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_pid_59_music_0.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/aw87xxx_pid_59_off_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_pid_59_off_0.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/aw87xxx_pid_59_rcv_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_pid_59_rcv_0.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/aw87xxx_pid_59_vmax_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_pid_59_vmax_0.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/aw87xxx_pid_59_voice_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_pid_59_voice_0.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/mt6635_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_coeff.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/mt6635_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_patch.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/novatek_ts_ct_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_ct_fw.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/novatek_ts_ct_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_ct_mp.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/soc2_2_ram_bt_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1_1_hdr.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/soc2_2_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1a_1_hdr.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/soc2_2_ram_mcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1_1_hdr.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/soc2_2_ram_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1a_1_hdr.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/soc2_2_ram_wifi_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1_1_hdr.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/soc2_2_ram_wifi_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1a_1_hdr.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/st21nfc_fw7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_fw7.bin \
    vendor/xiaomi/everpal/proprietary/vendor/firmware/txpowerctrl.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/txpowerctrl.cfg \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/020f0000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/020f0000000000000000000000000000.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/05120000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/05120000000000000000000000000000.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/06090000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/06090000000000000000000000000000.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/08010203000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08010203000000000000000000000000.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/08030000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08030000000000000000000000000000.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/08040000000000000000000000003419.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08040000000000000000000000003419.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/08050000000000000000000000003419.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08050000000000000000000000003419.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/08110000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08110000000000000000000000000000.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/14498ace2a8f11e880c8509a4c146f4c.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/14498ace2a8f11e880c8509a4c146f4c.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/3d08821c33a611e6a1fa089e01c83aa2.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/3d08821c33a611e6a1fa089e01c83aa2.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/40188311faf343488db888ad39496f9a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/40188311faf343488db888ad39496f9a.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/5020170115e016302017012521300000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/5020170115e016302017012521300000.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/655a4b46cd7711eaaafbf382a6988e7b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/655a4b46cd7711eaaafbf382a6988e7b.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/8aaaf201246000007143fe4f7c823c80.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/8aaaf201246000007143fe4f7c823c80.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/e5140b3376fa4c63ab18062caab2fb5c.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e5140b3376fa4c63ab18062caab2fb5c.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta \
    vendor/xiaomi/everpal/proprietary/vendor/thh/ta/fc32e4da17d342449b01c992d56d71bf.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/fc32e4da17d342449b01c992d56d71bf.ta

PRODUCT_PACKAGES += \
    libaedv \
    libbwc \
    libfile_op \
    libion_mtk \
    libion_ulit \
    libladder \
    libmtkcutils \
    libmtkproperty \
    libmtkrillog \
    libnvram \
    libnvram_sec \
    libmtk_drvb \
    audio.primary.mt6833 \
    audio.r_submix.mt6833 \
    sound_trigger.primary.default \
    libMtkSpeechEnh \
    lib_iir \
    lib_speech_enh \
    libalsautils.mt6833 \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libcvsd_mtk \
    libfgauge_gm30 \
    libmsbc_mtk \
    libmtklimiter_vendor \
    libmtkshifter_vendor \
    libnxp_extamp_intf \
    librt_extamp_intf \
    libsixth \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libvcodec_oal \
    libvcodec_utility \
    libvcodecdrv \
    libvcodecdrv_header_stub \
    libvpu5 \
    libvpud_vcodec \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    APUWareUtilsServer \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    arm.graphics-V1-ndk_platform \
    libGLES_mali \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    consumerir.common \
    fingerprint.fpc.default \
    fingerprint.goodix.default \
    gatekeeper.beanpod \
    gps.default \
    hwcomposer.mtk_common \
    sensors.elliptic \
    sensors.mt6833 \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.ccap@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.pq@2.13-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    vulkan.mali \
    imx355ofilm_mipi_raw_IdxMgr \
    imx355ofilm_mipi_raw_tuning \
    imx355sunny_mipi_raw_IdxMgr \
    imx355sunny_mipi_raw_tuning \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libAVCSecureVencCA \
    libCamera_gc02m1aacmipiraw_Default_Capture \
    libCamera_gc02m1aacmipiraw_Default_Preview \
    libCamera_gc02m1aacmipiraw_Default_Video \
    libCamera_gc02m1aacmipiraw_Flash_Capture \
    libCamera_gc02m1aacmipiraw_Scene_Capture \
    libCamera_gc02m1aacmipiraw_Scene_Capture_Zoom1 \
    libCamera_gc02m1aacmipiraw_Scene_Capture_Zoom2 \
    libCamera_gc02m1aacmipiraw_Scene_Preview \
    libCamera_gc02m1aacmipiraw_Scene_Preview_Zoom1 \
    libCamera_gc02m1aacmipiraw_Scene_Preview_Zoom2 \
    libCamera_gc02m1aacmipiraw_Scene_Professional_Capture \
    libCamera_gc02m1aacmipiraw_Scene_Professional_Preview \
    libCamera_gc02m1aacmipiraw_Video \
    libCamera_gc02m1ofilmmipiraw_Default_Capture \
    libCamera_gc02m1ofilmmipiraw_Default_Preview \
    libCamera_gc02m1ofilmmipiraw_Default_Video \
    libCamera_gc02m1ofilmmipiraw_Flash_Capture \
    libCamera_gc02m1ofilmmipiraw_Scene_Capture \
    libCamera_gc02m1ofilmmipiraw_Scene_Capture_Zoom1 \
    libCamera_gc02m1ofilmmipiraw_Scene_Capture_Zoom2 \
    libCamera_gc02m1ofilmmipiraw_Scene_Preview \
    libCamera_gc02m1ofilmmipiraw_Scene_Preview_Zoom1 \
    libCamera_gc02m1ofilmmipiraw_Scene_Preview_Zoom2 \
    libCamera_gc02m1ofilmmipiraw_Scene_Professional_Capture \
    libCamera_gc02m1ofilmmipiraw_Scene_Professional_Preview \
    libCamera_gc02m1ofilmmipiraw_Video \
    libCamera_imx355ofilmmipiraw_3rd_Capture \
    libCamera_imx355ofilmmipiraw_Color_Capture \
    libCamera_imx355ofilmmipiraw_E2EHDR_Preview \
    libCamera_imx355ofilmmipiraw_E2EHDR_Video \
    libCamera_imx355ofilmmipiraw_Face_Capture \
    libCamera_imx355ofilmmipiraw_Flash_Capture \
    libCamera_imx355ofilmmipiraw_Flash_Preview \
    libCamera_imx355ofilmmipiraw_HDR_Face_Capture \
    libCamera_imx355ofilmmipiraw_HDR_Scene_Capture \
    libCamera_imx355ofilmmipiraw_Professional \
    libCamera_imx355ofilmmipiraw_Professional_ZOOM1 \
    libCamera_imx355ofilmmipiraw_Professional_ZOOM2 \
    libCamera_imx355ofilmmipiraw_QQ_Capture \
    libCamera_imx355ofilmmipiraw_QQ_Capture_ChatMode \
    libCamera_imx355ofilmmipiraw_Scene_Capture \
    libCamera_imx355ofilmmipiraw_Scene_Preview \
    libCamera_imx355ofilmmipiraw_Torch_Capture \
    libCamera_imx355ofilmmipiraw_Video \
    libCamera_imx355ofilmmipiraw_portrait_capture_full \
    libCamera_imx355sunnymipiraw_3rd_Capture \
    libCamera_imx355sunnymipiraw_Color_Capture \
    libCamera_imx355sunnymipiraw_E2EHDR_Preview \
    libCamera_imx355sunnymipiraw_E2EHDR_Video \
    libCamera_imx355sunnymipiraw_Face_Capture \
    libCamera_imx355sunnymipiraw_Flash_Capture \
    libCamera_imx355sunnymipiraw_Flash_Preview \
    libCamera_imx355sunnymipiraw_HDR_Face_Capture \
    libCamera_imx355sunnymipiraw_HDR_Scene_Capture \
    libCamera_imx355sunnymipiraw_Professional \
    libCamera_imx355sunnymipiraw_Professional_ZOOM1 \
    libCamera_imx355sunnymipiraw_Professional_ZOOM2 \
    libCamera_imx355sunnymipiraw_QQ_Capture \
    libCamera_imx355sunnymipiraw_QQ_Capture_ChatMode \
    libCamera_imx355sunnymipiraw_Scene_Capture \
    libCamera_imx355sunnymipiraw_Scene_Preview \
    libCamera_imx355sunnymipiraw_Torch_Capture \
    libCamera_imx355sunnymipiraw_Video \
    libCamera_imx355sunnymipiraw_portrait_capture_full \
    libCamera_ov16a1qofilmmipiraw_3rd_Capture \
    libCamera_ov16a1qofilmmipiraw_3rd_Preview \
    libCamera_ov16a1qofilmmipiraw_3rd_Video \
    libCamera_ov16a1qofilmmipiraw_Default_Capture \
    libCamera_ov16a1qofilmmipiraw_Default_Preview \
    libCamera_ov16a1qofilmmipiraw_EIS_Video_1080P \
    libCamera_ov16a1qofilmmipiraw_EIS_Video_720P \
    libCamera_ov16a1qofilmmipiraw_FaceUnlock_Capture \
    libCamera_ov16a1qofilmmipiraw_Face_Capture \
    libCamera_ov16a1qofilmmipiraw_Face_Preview \
    libCamera_ov16a1qofilmmipiraw_FrontLight_Capture \
    libCamera_ov16a1qofilmmipiraw_FrontLight_Preview \
    libCamera_ov16a1qofilmmipiraw_HDR_Capture \
    libCamera_ov16a1qofilmmipiraw_ITS_CaptureYUV \
    libCamera_ov16a1qofilmmipiraw_P1_YUV \
    libCamera_ov16a1qofilmmipiraw_Panorama_Capture \
    libCamera_ov16a1qofilmmipiraw_Portrait_Capture \
    libCamera_ov16a1qofilmmipiraw_Portrait_Preview \
    libCamera_ov16a1qofilmmipiraw_QQWechat_Video \
    libCamera_ov16a1qofilmmipiraw_QQWechat_VideoCall \
    libCamera_ov16a1qofilmmipiraw_Scene_Capture \
    libCamera_ov16a1qofilmmipiraw_Scene_Preview \
    libCamera_ov16a1qofilmmipiraw_Video_1080 \
    libCamera_ov16a1qofilmmipiraw_Video_720 \
    libCamera_ov16a1qofilmmipiraw_Video_720p_120fps \
    libCamera_ov16a1qqtechmipiraw_3rd_Capture \
    libCamera_ov16a1qqtechmipiraw_3rd_Preview \
    libCamera_ov16a1qqtechmipiraw_3rd_Video \
    libCamera_ov16a1qqtechmipiraw_Default_Capture \
    libCamera_ov16a1qqtechmipiraw_Default_Preview \
    libCamera_ov16a1qqtechmipiraw_EIS_Video_1080P \
    libCamera_ov16a1qqtechmipiraw_EIS_Video_720P \
    libCamera_ov16a1qqtechmipiraw_FaceUnlock_Capture \
    libCamera_ov16a1qqtechmipiraw_Face_Capture \
    libCamera_ov16a1qqtechmipiraw_Face_Preview \
    libCamera_ov16a1qqtechmipiraw_FrontLight_Capture \
    libCamera_ov16a1qqtechmipiraw_FrontLight_Preview \
    libCamera_ov16a1qqtechmipiraw_HDR_Capture \
    libCamera_ov16a1qqtechmipiraw_ITS_CaptureYUV \
    libCamera_ov16a1qqtechmipiraw_P1_YUV \
    libCamera_ov16a1qqtechmipiraw_Panorama_Capture \
    libCamera_ov16a1qqtechmipiraw_Portrait_Capture \
    libCamera_ov16a1qqtechmipiraw_Portrait_Preview \
    libCamera_ov16a1qqtechmipiraw_QQWechat_Video \
    libCamera_ov16a1qqtechmipiraw_QQWechat_VideoCall \
    libCamera_ov16a1qqtechmipiraw_Scene_Capture \
    libCamera_ov16a1qqtechmipiraw_Scene_Preview \
    libCamera_ov16a1qqtechmipiraw_Video_1080 \
    libCamera_ov16a1qqtechmipiraw_Video_720 \
    libCamera_ov16a1qqtechmipiraw_Video_720p_120fps \
    libCamera_ov50c40ofilmmipiraw_3rd_Capture \
    libCamera_ov50c40ofilmmipiraw_3rd_Preview \
    libCamera_ov50c40ofilmmipiraw_Color_Capture \
    libCamera_ov50c40ofilmmipiraw_E2EHDR_Preview \
    libCamera_ov50c40ofilmmipiraw_E2EHDR_Video \
    libCamera_ov50c40ofilmmipiraw_Face_Capture \
    libCamera_ov50c40ofilmmipiraw_Face_Capture_50 \
    libCamera_ov50c40ofilmmipiraw_Flash_Capture \
    libCamera_ov50c40ofilmmipiraw_HDR_Face_Capture \
    libCamera_ov50c40ofilmmipiraw_HDR_Scene_Capture \
    libCamera_ov50c40ofilmmipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_ov50c40ofilmmipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_ov50c40ofilmmipiraw_LLHDR_Face_Capture \
    libCamera_ov50c40ofilmmipiraw_LLHDR_Scene_Capture \
    libCamera_ov50c40ofilmmipiraw_LLHDR_Scene_Capture_Zoom1 \
    libCamera_ov50c40ofilmmipiraw_LLHDR_Scene_Capture_Zoom2 \
    libCamera_ov50c40ofilmmipiraw_MFSR_Scene_Capture \
    libCamera_ov50c40ofilmmipiraw_MFSR_Scene_Capture_Zoom1 \
    libCamera_ov50c40ofilmmipiraw_P1_YUV \
    libCamera_ov50c40ofilmmipiraw_Professional_Capture \
    libCamera_ov50c40ofilmmipiraw_Professional_Capture_zoom1 \
    libCamera_ov50c40ofilmmipiraw_Professional_Capture_zoom2 \
    libCamera_ov50c40ofilmmipiraw_QQ_Capture \
    libCamera_ov50c40ofilmmipiraw_QQ_Capture_Call \
    libCamera_ov50c40ofilmmipiraw_Scene_Capture \
    libCamera_ov50c40ofilmmipiraw_Scene_Capture_50 \
    libCamera_ov50c40ofilmmipiraw_Scene_Preview \
    libCamera_ov50c40ofilmmipiraw_Scene_Preview_Zoom1 \
    libCamera_ov50c40ofilmmipiraw_Scene_Preview_Zoom2 \
    libCamera_ov50c40ofilmmipiraw_SuperNS_Face_Capture \
    libCamera_ov50c40ofilmmipiraw_SuperNS_Scene_Capture \
    libCamera_ov50c40ofilmmipiraw_SuperNS_Scene_Capture_Zoom1 \
    libCamera_ov50c40ofilmmipiraw_SuperNS_Scene_Capture_Zoom2 \
    libCamera_ov50c40ofilmmipiraw_SuperNS_Scene_Preview \
    libCamera_ov50c40ofilmmipiraw_SuperNS_Scene_Preview_Zoom1 \
    libCamera_ov50c40ofilmmipiraw_SuperNS_Scene_Preview_Zoom2 \
    libCamera_ov50c40ofilmmipiraw_Video_1080 \
    libCamera_ov50c40ofilmmipiraw_Video_1080P_60fps \
    libCamera_ov50c40ofilmmipiraw_Video_1080P_60fps_Zoom1 \
    libCamera_ov50c40ofilmmipiraw_Video_1080P_60fps_Zoom2 \
    libCamera_ov50c40ofilmmipiraw_Video_1080P_EIS \
    libCamera_ov50c40ofilmmipiraw_Video_480P \
    libCamera_ov50c40ofilmmipiraw_Video_720P \
    libCamera_ov50c40ofilmmipiraw_Video_720P_240fps \
    libCamera_ov50c40ofilmmipiraw_Video_720P_240fps_Zoom1 \
    libCamera_ov50c40ofilmmipiraw_Video_720P_240fps_Zoom2 \
    libCamera_ov50c40ofilmmipiraw_Video_720P_EIS \
    libCamera_ov50c40ofilmmipiraw_Video_EIS_Zoom1 \
    libCamera_ov50c40ofilmmipiraw_Video_EIS_Zoom2 \
    libCamera_ov50c40ofilmmipiraw_Video_Zoom1 \
    libCamera_ov50c40ofilmmipiraw_Video_Zoom2 \
    libCamera_ov50c40ofilmmipiraw_Wechat_Capture \
    libCamera_ov50c40ofilmmipiraw_Wechat_Capture_Call \
    libCamera_ov50c40ofilmmipiraw_portrait_capture_full \
    libCamera_ov50c40ofilmmipiraw_portrait_preview_full \
    libCamera_s5k3l6aacmipiraw_3rd_Capture \
    libCamera_s5k3l6aacmipiraw_3rd_Preview \
    libCamera_s5k3l6aacmipiraw_3rd_Video \
    libCamera_s5k3l6aacmipiraw_Default_Capture \
    libCamera_s5k3l6aacmipiraw_Default_Preview \
    libCamera_s5k3l6aacmipiraw_EIS_Video_1080P \
    libCamera_s5k3l6aacmipiraw_EIS_Video_720P \
    libCamera_s5k3l6aacmipiraw_FaceUnlock_Capture \
    libCamera_s5k3l6aacmipiraw_Face_Capture \
    libCamera_s5k3l6aacmipiraw_Face_Preview \
    libCamera_s5k3l6aacmipiraw_FrontLight_Capture \
    libCamera_s5k3l6aacmipiraw_FrontLight_Preview \
    libCamera_s5k3l6aacmipiraw_HDR_Capture \
    libCamera_s5k3l6aacmipiraw_ITS_CaptureYUV \
    libCamera_s5k3l6aacmipiraw_P1_YUV \
    libCamera_s5k3l6aacmipiraw_Panorama_Capture \
    libCamera_s5k3l6aacmipiraw_Portrait_Capture \
    libCamera_s5k3l6aacmipiraw_Portrait_Preview \
    libCamera_s5k3l6aacmipiraw_QQWechat_Video \
    libCamera_s5k3l6aacmipiraw_QQWechat_VideoCall \
    libCamera_s5k3l6aacmipiraw_Scene_Capture \
    libCamera_s5k3l6aacmipiraw_Scene_Preview \
    libCamera_s5k3l6aacmipiraw_Video_1080 \
    libCamera_s5k3l6aacmipiraw_Video_720 \
    libCamera_s5k3l6aacmipiraw_Video_720p_120fps \
    libCamera_s5k3l6qtechmipiraw_3rd_Capture \
    libCamera_s5k3l6qtechmipiraw_3rd_Preview \
    libCamera_s5k3l6qtechmipiraw_3rd_Video \
    libCamera_s5k3l6qtechmipiraw_Default_Capture \
    libCamera_s5k3l6qtechmipiraw_Default_Preview \
    libCamera_s5k3l6qtechmipiraw_EIS_Video_1080P \
    libCamera_s5k3l6qtechmipiraw_EIS_Video_720P \
    libCamera_s5k3l6qtechmipiraw_FaceUnlock_Capture \
    libCamera_s5k3l6qtechmipiraw_Face_Capture \
    libCamera_s5k3l6qtechmipiraw_Face_Preview \
    libCamera_s5k3l6qtechmipiraw_FrontLight_Capture \
    libCamera_s5k3l6qtechmipiraw_FrontLight_Preview \
    libCamera_s5k3l6qtechmipiraw_HDR_Capture \
    libCamera_s5k3l6qtechmipiraw_ITS_CaptureYUV \
    libCamera_s5k3l6qtechmipiraw_P1_YUV \
    libCamera_s5k3l6qtechmipiraw_Panorama_Capture \
    libCamera_s5k3l6qtechmipiraw_Portrait_Capture \
    libCamera_s5k3l6qtechmipiraw_Portrait_Preview \
    libCamera_s5k3l6qtechmipiraw_QQWechat_Video \
    libCamera_s5k3l6qtechmipiraw_QQWechat_VideoCall \
    libCamera_s5k3l6qtechmipiraw_Scene_Capture \
    libCamera_s5k3l6qtechmipiraw_Scene_Preview \
    libCamera_s5k3l6qtechmipiraw_Video_1080 \
    libCamera_s5k3l6qtechmipiraw_Video_720 \
    libCamera_s5k3l6qtechmipiraw_Video_720p_120fps \
    libCamera_s5kjn1aacmipiraw_3rd_Capture \
    libCamera_s5kjn1aacmipiraw_E2EHDR_Preview \
    libCamera_s5kjn1aacmipiraw_E2EHDR_Video \
    libCamera_s5kjn1aacmipiraw_Face_Capture \
    libCamera_s5kjn1aacmipiraw_Face_Capture_50 \
    libCamera_s5kjn1aacmipiraw_Flash_Capture \
    libCamera_s5kjn1aacmipiraw_Flash_Capture_Zoom1 \
    libCamera_s5kjn1aacmipiraw_Flash_Capture_Zoom2 \
    libCamera_s5kjn1aacmipiraw_HDR_Face_Capture \
    libCamera_s5kjn1aacmipiraw_HDR_Scene_Capture \
    libCamera_s5kjn1aacmipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_s5kjn1aacmipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_s5kjn1aacmipiraw_LLHDR_Face_Capture \
    libCamera_s5kjn1aacmipiraw_LLHDR_Scene_Capture \
    libCamera_s5kjn1aacmipiraw_LLHDR_Scene_Capture_Zoom1 \
    libCamera_s5kjn1aacmipiraw_LLHDR_Scene_Capture_Zoom2 \
    libCamera_s5kjn1aacmipiraw_MFSR_Scene_Capture \
    libCamera_s5kjn1aacmipiraw_MFSR_Scene_Capture_Zoom1 \
    libCamera_s5kjn1aacmipiraw_P1_YUV \
    libCamera_s5kjn1aacmipiraw_Panorama_Capture \
    libCamera_s5kjn1aacmipiraw_Professional_Capture \
    libCamera_s5kjn1aacmipiraw_Professional_Capture_face \
    libCamera_s5kjn1aacmipiraw_Professional_Capture_zoom1 \
    libCamera_s5kjn1aacmipiraw_Professional_Capture_zoom2 \
    libCamera_s5kjn1aacmipiraw_Professional_Preview \
    libCamera_s5kjn1aacmipiraw_Professional_Preview_face \
    libCamera_s5kjn1aacmipiraw_QQ_Capture \
    libCamera_s5kjn1aacmipiraw_QQ_Capture_Call \
    libCamera_s5kjn1aacmipiraw_Scene_Capture \
    libCamera_s5kjn1aacmipiraw_Scene_Capture_50 \
    libCamera_s5kjn1aacmipiraw_Scene_Preview \
    libCamera_s5kjn1aacmipiraw_Scene_Preview_Zoom1 \
    libCamera_s5kjn1aacmipiraw_Scene_Preview_Zoom2 \
    libCamera_s5kjn1aacmipiraw_SuperNS_Face_Capture \
    libCamera_s5kjn1aacmipiraw_SuperNS_Scene_Capture \
    libCamera_s5kjn1aacmipiraw_SuperNS_Scene_Capture_Zoom1 \
    libCamera_s5kjn1aacmipiraw_SuperNS_Scene_Capture_Zoom2 \
    libCamera_s5kjn1aacmipiraw_SuperNS_Scene_Preview_Zoom1 \
    libCamera_s5kjn1aacmipiraw_SuperNS_Scene_Preview_Zoom2 \
    libCamera_s5kjn1aacmipiraw_Video_1080 \
    libCamera_s5kjn1aacmipiraw_Video_1080P_60fps \
    libCamera_s5kjn1aacmipiraw_Video_1080P_60fps_Zoom1 \
    libCamera_s5kjn1aacmipiraw_Video_1080P_60fps_Zoom2 \
    libCamera_s5kjn1aacmipiraw_Video_1080P_EIS \
    libCamera_s5kjn1aacmipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_s5kjn1aacmipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_s5kjn1aacmipiraw_Video_1080_Zoom1 \
    libCamera_s5kjn1aacmipiraw_Video_1080_Zoom2 \
    libCamera_s5kjn1aacmipiraw_Video_480P \
    libCamera_s5kjn1aacmipiraw_Video_720P \
    libCamera_s5kjn1aacmipiraw_Video_720P_240fps \
    libCamera_s5kjn1aacmipiraw_Video_720P_240fps_Zoom1 \
    libCamera_s5kjn1aacmipiraw_Video_720P_240fps_Zoom2 \
    libCamera_s5kjn1aacmipiraw_Video_720P_EIS \
    libCamera_s5kjn1aacmipiraw_Video_720P_EIS_Zoom1 \
    libCamera_s5kjn1aacmipiraw_Video_720P_EIS_Zoom2 \
    libCamera_s5kjn1aacmipiraw_Video_720P_Zoom1 \
    libCamera_s5kjn1aacmipiraw_Video_720P_Zoom2 \
    libCamera_s5kjn1aacmipiraw_Wechat_Capture \
    libCamera_s5kjn1aacmipiraw_Wechat_Capture_Call \
    libCamera_s5kjn1aacmipiraw_portrait_capture_full \
    libCamera_s5kjn1aacmipiraw_portrait_preview_full \
    libCamera_s5kjn1ofilmmipiraw_3rd_Capture \
    libCamera_s5kjn1ofilmmipiraw_E2EHDR_Preview \
    libCamera_s5kjn1ofilmmipiraw_E2EHDR_Video \
    libCamera_s5kjn1ofilmmipiraw_Face_Capture \
    libCamera_s5kjn1ofilmmipiraw_Face_Capture_50 \
    libCamera_s5kjn1ofilmmipiraw_Flash_Capture \
    libCamera_s5kjn1ofilmmipiraw_Flash_Capture_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_Flash_Capture_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_HDR_Face_Capture \
    libCamera_s5kjn1ofilmmipiraw_HDR_Scene_Capture \
    libCamera_s5kjn1ofilmmipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_LLHDR_Face_Capture \
    libCamera_s5kjn1ofilmmipiraw_LLHDR_Scene_Capture \
    libCamera_s5kjn1ofilmmipiraw_LLHDR_Scene_Capture_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_LLHDR_Scene_Capture_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_MFSR_Scene_Capture \
    libCamera_s5kjn1ofilmmipiraw_MFSR_Scene_Capture_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_P1_YUV \
    libCamera_s5kjn1ofilmmipiraw_Panorama_Capture \
    libCamera_s5kjn1ofilmmipiraw_Professional_Capture \
    libCamera_s5kjn1ofilmmipiraw_Professional_Capture_face \
    libCamera_s5kjn1ofilmmipiraw_Professional_Capture_zoom1 \
    libCamera_s5kjn1ofilmmipiraw_Professional_Capture_zoom2 \
    libCamera_s5kjn1ofilmmipiraw_Professional_Preview \
    libCamera_s5kjn1ofilmmipiraw_Professional_Preview_face \
    libCamera_s5kjn1ofilmmipiraw_QQ_Capture \
    libCamera_s5kjn1ofilmmipiraw_QQ_Capture_Call \
    libCamera_s5kjn1ofilmmipiraw_Scene_Capture \
    libCamera_s5kjn1ofilmmipiraw_Scene_Capture_50 \
    libCamera_s5kjn1ofilmmipiraw_Scene_Preview \
    libCamera_s5kjn1ofilmmipiraw_Scene_Preview_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_Scene_Preview_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_SuperNS_Face_Capture \
    libCamera_s5kjn1ofilmmipiraw_SuperNS_Scene_Capture \
    libCamera_s5kjn1ofilmmipiraw_SuperNS_Scene_Capture_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_SuperNS_Scene_Capture_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_SuperNS_Scene_Preview_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_SuperNS_Scene_Preview_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_Video_1080 \
    libCamera_s5kjn1ofilmmipiraw_Video_1080P_60fps \
    libCamera_s5kjn1ofilmmipiraw_Video_1080P_60fps_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_Video_1080P_60fps_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_Video_1080P_EIS \
    libCamera_s5kjn1ofilmmipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_Video_1080_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_Video_1080_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_Video_480P \
    libCamera_s5kjn1ofilmmipiraw_Video_720P \
    libCamera_s5kjn1ofilmmipiraw_Video_720P_240fps \
    libCamera_s5kjn1ofilmmipiraw_Video_720P_240fps_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_Video_720P_240fps_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_Video_720P_EIS \
    libCamera_s5kjn1ofilmmipiraw_Video_720P_EIS_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_Video_720P_EIS_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_Video_720P_Zoom1 \
    libCamera_s5kjn1ofilmmipiraw_Video_720P_Zoom2 \
    libCamera_s5kjn1ofilmmipiraw_Wechat_Capture \
    libCamera_s5kjn1ofilmmipiraw_Wechat_Capture_Call \
    libCamera_s5kjn1ofilmmipiraw_portrait_capture_full \
    libCamera_s5kjn1ofilmmipiraw_portrait_preview_full \
    libCamera_s5kjn1sunnymipiraw_3rd_Capture \
    libCamera_s5kjn1sunnymipiraw_Color_Capture \
    libCamera_s5kjn1sunnymipiraw_E2EHDR_Preview \
    libCamera_s5kjn1sunnymipiraw_E2EHDR_Video \
    libCamera_s5kjn1sunnymipiraw_Face_Capture \
    libCamera_s5kjn1sunnymipiraw_Face_Capture_50 \
    libCamera_s5kjn1sunnymipiraw_Flash_Capture \
    libCamera_s5kjn1sunnymipiraw_Flash_Capture_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_Flash_Capture_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_HDR_Face_Capture \
    libCamera_s5kjn1sunnymipiraw_HDR_Scene_Capture \
    libCamera_s5kjn1sunnymipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_LLHDR_Face_Capture \
    libCamera_s5kjn1sunnymipiraw_LLHDR_Scene_Capture \
    libCamera_s5kjn1sunnymipiraw_LLHDR_Scene_Capture_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_LLHDR_Scene_Capture_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_MFSR_Scene_Capture \
    libCamera_s5kjn1sunnymipiraw_MFSR_Scene_Capture_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_P1_YUV \
    libCamera_s5kjn1sunnymipiraw_Panorama_Capture \
    libCamera_s5kjn1sunnymipiraw_Professional_Capture \
    libCamera_s5kjn1sunnymipiraw_Professional_Capture_face \
    libCamera_s5kjn1sunnymipiraw_Professional_Capture_zoom1 \
    libCamera_s5kjn1sunnymipiraw_Professional_Capture_zoom2 \
    libCamera_s5kjn1sunnymipiraw_Professional_Preview \
    libCamera_s5kjn1sunnymipiraw_Professional_Preview_face \
    libCamera_s5kjn1sunnymipiraw_QQ_Capture \
    libCamera_s5kjn1sunnymipiraw_QQ_Capture_Call \
    libCamera_s5kjn1sunnymipiraw_Scene_Capture \
    libCamera_s5kjn1sunnymipiraw_Scene_Capture_50 \
    libCamera_s5kjn1sunnymipiraw_Scene_Preview \
    libCamera_s5kjn1sunnymipiraw_Scene_Preview_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_Scene_Preview_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_SuperNS_Face_Capture \
    libCamera_s5kjn1sunnymipiraw_SuperNS_Scene_Capture \
    libCamera_s5kjn1sunnymipiraw_SuperNS_Scene_Capture_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_SuperNS_Scene_Capture_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_SuperNS_Scene_Preview \
    libCamera_s5kjn1sunnymipiraw_SuperNS_Scene_Preview_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_SuperNS_Scene_Preview_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_Video_1080 \
    libCamera_s5kjn1sunnymipiraw_Video_1080P_60fps \
    libCamera_s5kjn1sunnymipiraw_Video_1080P_60fps_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_Video_1080P_60fps_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_Video_1080P_EIS \
    libCamera_s5kjn1sunnymipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_Video_1080_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_Video_1080_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_Video_480P \
    libCamera_s5kjn1sunnymipiraw_Video_720P \
    libCamera_s5kjn1sunnymipiraw_Video_720P_240fps \
    libCamera_s5kjn1sunnymipiraw_Video_720P_240fps_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_Video_720P_240fps_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_Video_720P_EIS \
    libCamera_s5kjn1sunnymipiraw_Video_720P_EIS_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_Video_720P_EIS_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_Video_720P_Zoom1 \
    libCamera_s5kjn1sunnymipiraw_Video_720P_Zoom2 \
    libCamera_s5kjn1sunnymipiraw_Wechat_Capture \
    libCamera_s5kjn1sunnymipiraw_Wechat_Capture_Call \
    libCamera_s5kjn1sunnymipiraw_portrait_capture_full \
    libCamera_s5kjn1sunnymipiraw_portrait_preview_full \
    libDR \
    libDefaultFpsActor \
    libFrameRecord \
    libJpgEncPipe \
    libNoFpsActor \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTEECommon \
    lib_bsscore \
    lib_sr_models \
    libaaa_ltm \
    libaaa_ltmx \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libaalservice \
    libaiawb_moon \
    libaiawb_moon_model \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaiawb_sun_model \
    libalCFR \
    libalLDC \
    libalhLDC \
    libanc_dc_base \
    libanc_dc_plugin_xiaomi_v2 \
    libapu_mdw \
    libapusys \
    libapusys_edma \
    libarcsoft_beautyshot \
    libarcsoft_low_light_hdr \
    libarcsoft_super_night_raw \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libbluetooth_mtk \
    libbt-vendor \
    libc++_shared \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.seninfn3d \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.3dnr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.utility \
    libcamalgo.vpudsdn \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.custom.pd_buf_mgr \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcamera_scene \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.lens \
    libcameracustom \
    libcameracustom_all_sensor_modules \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libdip_drv \
    libdip_imem \
    libdip_postproc \
    libdre \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libforkexecwrap \
    libformatter \
    libgamehdr \
    libged \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_gp_client \
    libgz_uree \
    libhdrvideo \
    libheichal \
    libhfmanager \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libimgsensorca \
    libimsg_log \
    libispcameraca \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libksensor \
    liblpcnr \
    libm4u \
    libmfllcore \
    libmiStereoFactoryRemapBasicLib \
    libmiStereoFactoryRemapLib \
    libmialgo_sd \
    libmialgo_utils \
    libmialgoengine \
    libmibokeh_mt6873 \
    libmipc \
    libmml \
    libmnetlink_v104 \
    libmnl \
    libmpbase \
    libmsnr \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtkares \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkcam_vsync_util \
    libmtkconfig \
    libmtkconfigutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkrilutils \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libneuroeara \
    libneuron_adapter \
    libneuron_platform \
    libneuropilot_hal_utils \
    libnir_neon_driver_ndk.mtk.vndk \
    libnotifyaudiohal \
    liboemcrypto \
    libpq_cust_base \
    libpqframework \
    libpqparamparser \
    libratconfig \
    librgbwlightsensor \
    librilfusion \
    libsdk_sr \
    libsensor_custom \
    libstereoinfoaccessor_vsdof \
    libstorage_otp \
    libsysenv \
    libteeclientjni \
    libteeclientjni@1.1 \
    libteei_daemon_vfs \
    libtlcWidevineModularDrm \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libvia-ril \
    libviamipc-ril \
    libvideofilter_only \
    libvidhance \
    libwa_depth \
    libwa_refocus \
    libwa_rtdof \
    libwifi-hal-mtk \
    libwpfa \
    libwvhidl \
    libxmi_high_dynamic_range \
    libwvdrmengine \
    libaiselector \
    libdpframework \
    libnir_neon_driver \
    libpq_prot \
    libmtkcam_streaminfo_plugin-p1stt \
    ov16a1qofilm_mipi_raw_IdxMgr \
    ov16a1qofilm_mipi_raw_tuning \
    ov16a1qqtech_mipi_raw_IdxMgr \
    ov16a1qqtech_mipi_raw_tuning \
    ov50c40ofilm_mipi_raw_IdxMgr \
    ov50c40ofilm_mipi_raw_tuning \
    s5kjn1sunny_mipi_raw_IdxMgr \
    s5kjn1sunny_mipi_raw_tuning \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.mediatek.hardware.videotelephony@1.0 \
    HotwordEnrollmentOKGoogleRISCV \
    HotwordEnrollmentXGoogleRISCV \
    com.android.hotwordenrollment.common.util \
    android.hardware.neuralnetworks@1.3-service-mtk-gpu.xml \
    gnss-mediatek.xml \
    gnss@2.1-service.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_media_c2_V1_2_default.xml \
    batterysecret \
    bp_kmsetkey_ca \
    ccci_mdinit \
    ccci_rpcd \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.1-service.beanpod \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks@1.3-service-mtk-neuron \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vtservice_hidl \
    lib3a.ccu.ddr \
    lib3a.ccu.dm \
    lib3a.ccu.pm \
    mi_thermald \
    mnld \
    mtk_agpsd \
    netdagent \
    nvram_daemon \
    teei_daemon \
    vpud \
    wlan_assistant \
    wmt_launcher \
    wmt_loader

PRODUCT_PACKAGES += \
    vendor_lib_libmtk_drvb_so \
    vendor_lib64_libaiselector_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_prot_so
